In [1]:
import pandas as pd 
import numpy as np

In [12]:
from sklearn import datasets


X_disbalance, y_disbalance = datasets.make_classification(
    n_samples=20,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2, 
    random_state=2,
    weights=(0.9, 0.1)
)

X_disbalance, y_disbalance

(array([[ 0.66930255, -0.35556485],
        [ 0.96417816, -0.37583852],
        [-1.1177634 , -0.85116212],
        [-0.26257856, -1.50684503],
        [ 1.27004352, -2.01184296],
        [ 0.72576002,  0.53047004],
        [-0.77546276, -0.9788468 ],
        [ 1.03317819, -0.88253973],
        [ 0.7545933 ,  1.11410377],
        [ 0.37973272,  0.79063286],
        [ 1.2610877 , -1.3003902 ],
        [-2.44391337, -0.56099989],
        [-0.66010918, -1.0843706 ],
        [-0.90474756,  0.59452911],
        [-2.51019507, -0.30991259],
        [ 0.9153728 ,  0.08016006],
        [ 1.28700068, -1.90827144],
        [-1.94625628, -0.53314708],
        [-0.85711456, -1.16420714],
        [-1.33222706, -0.85982898]]),
 array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]))

In [11]:
pred = [0 for i in range(20)]

In [13]:
pred_df_disbalance = pd.DataFrame({
    'ground truth': y_disbalance,
    'prediction': pred
})

pred_df_disbalance

    ground truth  prediction
0              0           0
1              0           0
2              0           0
3              0           0
4              0           0
5              1           0
6              0           0
7              0           0
8              0           0
9              0           0
10             0           0
11             0           0
12             0           0
13             1           0
14             0           0
15             0           0
16             0           0
17             0           0
18             0           0
19             0           0

In [15]:
pred_df_disbalance['right']  = pred_df_disbalance['ground truth'] == pred_df_disbalance['prediction']
pred_df_disbalance

    ground truth  prediction  right
0              0           0   True
1              0           0   True
2              0           0   True
3              0           0   True
4              0           0   True
5              1           0  False
6              0           0   True
7              0           0   True
8              0           0   True
9              0           0   True
10             0           0   True
11             0           0   True
12             0           0   True
13             1           0  False
14             0           0   True
15             0           0   True
16             0           0   True
17             0           0   True
18             0           0   True
19             0           0   True

In [38]:
without_pers = pred_df_disbalance['right'].sum() / pred_df_disbalance['right'].shape[0]

In [40]:
without_pers

0.9

In [41]:
print(f'without_pers : {without_pers}%')

without_pers : 0.9%

(20,)